### PR TITLE
fix destructuring syntax to meet clojure/core.specs.alpha

### PR DESCRIPTION
**Pull request by tobiasquinn**
Fixes destructures so they meet clojure/core.specs.alpha specification

### CODE REVIEW

**Comment by madvas** [comment]
Can you link me please where this is noted in specification?

**Comment by tobiasquinn** [comment]
Not sure exactly which part of the spec but I'm using shadow-cljs to compile and I believe this validates against clojure/core.specs.alpha here is an example with the relevant specs:

Call to cljs.core/defn did not conform to spec
-- Syntax error -------------------

  (... [... [{:keys [:gql-name->kw], :or {:gql-name->kw identity}}]] ...)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

has extra input

-- Relevant specs -------

:clojure.core.specs.alpha/seq-binding-form:
  (clojure.spec.alpha/and
   clojure.core/vector?
   (clojure.spec.alpha/cat
    :elems
    (clojure.spec.alpha/* :clojure.core.specs.alpha/binding-form)
    :rest
    (clojure.spec.alpha/?
     (clojure.spec.alpha/cat
      :amp
      #{'&}
      :form
      :clojure.core.specs.alpha/binding-form))
    :as
    (clojure.spec.alpha/?
     (clojure.spec.alpha/cat
      :as
      #{:as}
      :sym
      :clojure.core.specs.alpha/local-name))))
:clojure.core.specs.alpha/binding-form:
  (clojure.spec.alpha/or
   :sym
   :clojure.core.specs.alpha/local-name
   :seq
   :clojure.core.specs.alpha/seq-binding-form
   :map
   :clojure.core.specs.alpha/map-binding-form)
:clojure.core.specs.alpha/arg-list:
  (clojure.spec.alpha/and
   clojure.core/vector?
   (clojure.spec.alpha/cat
    :args
    (clojure.spec.alpha/* :clojure.core.specs.alpha/binding-form)
    :varargs
    (clojure.spec.alpha/?
     (clojure.spec.alpha/cat
      :amp
      #{'&}
      :form
      :clojure.core.specs.alpha/binding-form))))
:clojure.core.specs.alpha/args+body:
  (clojure.spec.alpha/cat
   :args
   :clojure.core.specs.alpha/arg-list
   :body
   (clojure.spec.alpha/alt
    :prepost+body
    (clojure.spec.alpha/cat
     :prepost
     clojure.core/map?
     :body
     (clojure.spec.alpha/+ clojure.core/any?))
    :body
    (clojure.spec.alpha/* clojure.core/any?)))
:clojure.core.specs.alpha/defn-args:
  (clojure.spec.alpha/cat
   :name
   clojure.core/simple-symbol?
   :docstring
   (clojure.spec.alpha/? clojure.core/string?)
   :meta
   (clojure.spec.alpha/? clojure.core/map?)
   :bs
   (clojure.spec.alpha/alt
    :arity-1
    :clojure.core.specs.alpha/args+body
    :arity-n
    (clojure.spec.alpha/cat
     :bodies
     (clojure.spec.alpha/+
      (clojure.spec.alpha/spec :clojure.core.specs.alpha/args+body))
     :attr
     (clojure.spec.alpha/? clojure.core/map?))))

-- Spec failed --------------------

  (... [... [{:keys [:gql-name->kw], :or {:gql-name->kw identity}}]] ...)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

should satisfy

  vector?

-- Relevant specs -------

:clojure.core.specs.alpha/ns-keys:
  (clojure.spec.alpha/tuple
   (clojure.spec.alpha/and
    clojure.core/qualified-keyword?
    (fn*
     [p1__45#]
     (clojure.core/-> p1__45# clojure.core/name #{"syms" "keys"})))
   (clojure.spec.alpha/coll-of
    clojure.core/simple-symbol?
    :kind
    clojure.core/vector?))
:clojure.core.specs.alpha/map-binding:
  (clojure.spec.alpha/tuple
   :clojure.core.specs.alpha/binding-form
   clojure.core/any?)
:clojure.core.specs.alpha/map-bindings:
  (clojure.spec.alpha/every
   (clojure.spec.alpha/or
    :mb
    :clojure.core.specs.alpha/map-binding
    :nsk
    :clojure.core.specs.alpha/ns-keys
    :msb
    (clojure.spec.alpha/tuple
     #{:as :or :syms :keys :strs}
     clojure.core/any?))
   :into
   {})
:clojure.core.specs.alpha/map-binding-form:
  (clojure.spec.alpha/merge
   :clojure.core.specs.alpha/map-bindings
   :clojure.core.specs.alpha/map-special-binding)
:clojure.core.specs.alpha/binding-form:
  (clojure.spec.alpha/or
   :sym
   :clojure.core.specs.alpha/local-name
   :seq
   :clojure.core.specs.alpha/seq-binding-form
   :map
   :clojure.core.specs.alpha/map-binding-form)
:clojure.core.specs.alpha/arg-list:
  (clojure.spec.alpha/and
   clojure.core/vector?
   (clojure.spec.alpha/cat
    :args
    (clojure.spec.alpha/* :clojure.core.specs.alpha/binding-form)
    :varargs
    (clojure.spec.alpha/?
     (clojure.spec.alpha/cat
      :amp
      #{'&}
      :form
      :clojure.core.specs.alpha/binding-form))))
:clojure.core.specs.alpha/args+body:
  (clojure.spec.alpha/cat
   :args
   :clojure.core.specs.alpha/arg-list
   :body
   (clojure.spec.alpha/alt
    :prepost+body
    (clojure.spec.alpha/cat
     :prepost
     clojure.core/map?
     :body
     (clojure.spec.alpha/+ clojure.core/any?))
    :body
    (clojure.spec.alpha/* clojure.core/any?)))
:clojure.core.specs.alpha/defn-args:
  (clojure.spec.alpha/cat
   :name
   clojure.core/simple-symbol?
   :docstring
   (clojure.spec.alpha/? clojure.core/string?)
   :meta
   (clojure.spec.alpha/? clojure.core/map?)
   :bs
   (clojure.spec.alpha/alt
    :arity-1
    :clojure.core.specs.alpha/args+body
    :arity-n
    (clojure.spec.alpha/cat
     :bodies
     (clojure.spec.alpha/+
      (clojure.spec.alpha/spec :clojure.core.specs.alpha/args+body))
     :attr
     (clojure.spec.alpha/? clojure.core/map?))))

-- Spec failed --------------------

  (... [& ...] ...)
        ^

should satisfy

  vector?

-- Relevant specs -------

:clojure.core.specs.alpha/arg-list:
  (clojure.spec.alpha/and
   clojure.core/vector?
   (clojure.spec.alpha/cat
    :args
    (clojure.spec.alpha/* :clojure.core.specs.alpha/binding-form)
    :varargs
    (clojure.spec.alpha/?
     (clojure.spec.alpha/cat
      :amp
      #{'&}
      :form
      :clojure.core.specs.alpha/binding-form))))
:clojure.core.specs.alpha/args+body:
  (clojure.spec.alpha/cat
   :args
   :clojure.core.specs.alpha/arg-list
   :body
   (clojure.spec.alpha/alt
    :prepost+body
    (clojure.spec.alpha/cat
     :prepost
     clojure.core/map?
     :body
     (clojure.spec.alpha/+ clojure.core/any?))
    :body
    (clojure.spec.alpha/* clojure.core/any?)))
:clojure.core.specs.alpha/defn-args:
  (clojure.spec.alpha/cat
   :name
   clojure.core/simple-symbol?
   :docstring
   (clojure.spec.alpha/? clojure.core/string?)
   :meta
   (clojure.spec.alpha/? clojure.core/map?)
   :bs
   (clojure.spec.alpha/alt
    :arity-1
    :clojure.core.specs.alpha/args+body
    :arity-n
    (clojure.spec.alpha/cat
     :bodies
     (clojure.spec.alpha/+
      (clojure.spec.alpha/spec :clojure.core.specs.alpha/args+body))
     :attr
     (clojure.spec.alpha/? clojure.core/map?))))

-------------------------
Detected 3 errors

--------------------------------------------------------------------------------
 336 |                                  :or {:gql-name->kw identity}}]]
 337 |   (fn [{:keys [:graph :entities]} args _ info]
 338 |     (let [name (aget info "fieldName")
 339 |           args (serialize-args args {:gql-name->kw gql-name->kw})
--------------------------------------------------------------------------------

**Comment by madvas** [comment]
I actually think only part `:or {:gql-name->kw identity}}` is invalid syntax. 
`:keys [:gql-name->kw]` is definitely valid syntax, it's used throughout the whole code. 

https://github.com/district0x/district-ui-graphql/pull/3/files#diff-7ae5f21e2c870a3de39982f3b865ed73L413
Is probably valid true, but not 100% sure. 

Can you try it with leaving `:keys [:gql-name->kw]` as it is, please?

**Comment by tobiasquinn** [comment]
Yes, you're right, leaving `:keys [:gql-name->kw]` as it is works but, lines 413 and 414 still need the changes to pass spec test

**Comment by madvas** [comment]
yep, so can you update PR so `:keys [:gql-name->kw]` stays as it is? Thank you

**Comment by tobiasquinn** [comment]
Done

**Comment by madvas** [comment]
Thanks!

**Pull request merged**
